ALTER TABLE `tickets`
    MODIFY COLUMN `status` ENUM('AVAILABLE', 'QUEUED', 'HOLD', 'BOOKED') NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE `seat_segment_inventory`
    MODIFY COLUMN `status` ENUM('AVAILABLE', 'QUEUED', 'HOLD', 'BOOKED', 'BLOCKED') NOT NULL DEFAULT 'AVAILABLE';
