ALTER TABLE users
    ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS nationality VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS reward_points INT DEFAULT 0,
    ADD COLUMN IF NOT EXISTS membership_rank VARCHAR(50) DEFAULT 'BRONZE',
    ADD COLUMN IF NOT EXISTS is_identity_verified TINYINT(1) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) NULL;
